### ISSUE TITLE
why not use ius-release?

### ISSUE THREAD

**Issue by b-harper** [kemra102/puppet-ius#3]
Greetings,

I am curious why 'manually' created IUS repository configuration files are used instead of using the ius-release package?   Is there some advantage within Puppet?  I personally use Salt-Stack and don't know much about Puppet.   

I (re)discovered this repository while addressing an [issue with a bash bootstrap script](https://github.com/iuscommunity/setup.ius.io/pull/2#issuecomment-239824469).  Also, I am considering mentioned this repository in our [automation examples](https://github.com/iuscommunity/automation-examples), see this [issue](https://github.com/iuscommunity/automation-examples/issues/3).

**Comment by kemra102** [comment]
Hi @b-harper 

People using Puppet usually prefer the yum repo files to be directly managed by Puppet as this means they can take advantage of the file resources ability to manage the contents of the directory like so:

```puppet
file { '/etc/yum.repos.d':
  ensure  => 'directory',
  recurse => true,
  purge    => true
}
```

This will mean that any Yum repo file not managed by Puppet will be removed from a system.

**Comment by b-harper** [comment]
Hey @kemra102,

Thanks for the timely reply.  I could see how that could be useful for some.  In general, IUS will continue to encourage the use of the ius-release package.  We also recognize that there are some use cases where it is not the best solution.

I would recommend watching the [ius-release GitHub repository][0], so you are aware if/when we make any changes.

-Ben

[0]: https://github.com/iuscommunity-pkg/ius-release
